### ISSUE TITLE
Via_region_data.json file not found error while it is there in train and test dataset

### ISSUE THREAD

**Issue by ayush1427** [girijesh18/car-damage-detection#1]
I am trying to train bottle.py file on car-damage-detection dataset. Both the train and test datasets contain via_region_data.json file. However the error that I am getting is “via_region_data.json” file not available. Trying to run in google colab with the below command. 

!python bottle.py train --dataset=dataset15/ --weights=coco 

Traceback (most recent call last):
  File "bottle.py", line 368, in <module>
    train(model)
  File "bottle.py", line 183, in train
    dataset_train.load_custom(args.dataset, "train")
  File "bottle.py", line 114, in load_custom
    annotations1 = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset15/train/via_region_data.json' 

Is there anything that I am missing.

**Comment by Rakesh-MS-91** [comment]
@ayush1427 FileNotFoundError: This error will only occurs when the required file is not in your directory.  Just recheck the google drive location provided i your code.
